name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - master


jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Rust compilation prerequisites
        run: |
          sudo apt update
          sudo apt install -y \
            protobuf-compiler
          rustup target add wasm32-unknown-unknown
          rustup component add rustfmt clippy rust-src

      # We've run into out-of-disk error when compiling Polkadot in the next step, so we free up some space this way.
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # 1.3.1
        with:
          android: true # This alone is a 12 GB save.
          # We disable the rest because it caused some problems. (they're enabled by default)
          # The Android removal is enough.
          dotnet: false
          haskell: false
          large-packages: false
          swap-storage: false

      - name: Check if it compiles
        id: check-compilation
        run: cargo check && cargo test
        timeout-minutes: 90
